### ISSUE TITLE
Sometimes the toolbox is empty

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-intellij#15]
It needs to explain why the toolbox is empty, or it shouldn't be empty

![image](https://github.com/smallcloudai/refact-intellij/assets/18546213/c2e1dec8-a13b-4b14-8c3f-7e327df30de0)

**Comment by nikitakoselev** [comment]
If that helps, the project is a clone from https://exercism.org/tracks/go/exercises/resistor-color-duo
After some time the table on the right got populated, but I am not sure if that was due to time passed or some other factors, like reinstalling of the plugin.

The latest state:
![image](https://github.com/smallcloudai/refact-intellij/assets/6383738/51613eb5-f308-4cd6-8bd4-a6706ac16a3e)

**Comment by FWLamb** [comment]
When I use self hosting, this issue occurs？Why?

**Comment by hazratisulton** [comment]
Toolbox removed from plugin.
